---
- name: Disable Consistent Network Device Naming (CNDN)
  hosts: your_target_servers
  become: yes  # Ensure you have necessary privileges

  tasks:
    - name: Remove 80-net-setup-link.rules
      file:
        path: /etc/udev/rules.d/80-net-setup-link.rules
        state: absent
      notify: Reload udev

    - name: Configure Grub to Disable CNDN
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
      notify: Update Grub

  handlers:
    - name: Reload udev
      systemd:
        name: systemd-udevd
        state: restarted

    - name: Update Grub
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
