---
- name: Check and install CentOS Stream 9 repositories
  hosts: test
  become: yes  # This will use sudo to run commands as root

  tasks:
    - name: Check if the system is CentOS Stream 9
      command: cat /etc/redhat-release
      register: centos_release
      changed_when: false
      failed_when: false

    - name: Install CentOS Stream 9 base repository
      yum_repository:
        name: CentOS-Stream-Base
        description: CentOS Stream 9 Base Repository
        baseurl: https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1

    - name: Install Docker CE stable repository
      yum_repository:
        name: Docker-CE
        description: Docker CE Stable Repository
        baseurl: https://download.docker.com/linux/centos/9/x86_64/stable
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1

    - name: Install Extra Packages for Enterprise Linux 9 repository
      yum_repository:
        name: EPEL-9
        description: Extra Packages for Enterprise Linux 9 Repository
        baseurl: https://dl.fedoraproject.org/pub/epel/9/Everything/x86_64/
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1

    - name: Install PostgreSQL 15 repository
      yum_repository:
        name: PostgreSQL-15
        description: PostgreSQL 15 Repository for CentOS Stream 9
        baseurl: https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-9-x86_64
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1

    - name: Install Selected packages from remi repository
      yum_repository:
        name: REMI-9
        description: Selected packages from Remi Repository for CentOS Stream 9
        baseurl: https://rpms.remirepo.net/enterprise/9/remi/x86_64/
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1

    - name: Install CentOS Stream 9 AppStream repository
      yum_repository:
        name: CentOS-Stream-AppStream
        description: CentOS Stream 9 AppStream Repository
        baseurl: https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/
        gpgcheck: yes
        enabled: yes
      when: centos_release.stdout.find("CentOS Stream release 9") != -1
