---
- name: Install and configure web server, Let's Encrypt, Fail2ban, and firewall
  hosts: your_target_host
  become: true

  tasks:
    - name: Update the package cache
      dnf:
        name: '*'
        state: latest

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - httpd
        - iptables
        - iptables-services
        - git
        - certbot
        - fail2ban

    - name: Start and enable services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - httpd
        - iptables
        - fail2ban

    - name: Allow SSH access from specific IPs
      command: iptables -A INPUT -p tcp --dport 22 -s {{ item }} -j ACCEPT
      loop:
        - 0.0.0.0 #allow ssh connections from this ip

    - name: Allow HTTP (port 80) from anywhere
      command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

    - name: Allow HTTPS (port 443) from anywhere
      command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT

    - name: Drop all other incoming traffic
      command: iptables -A INPUT -j DROP

    - name: Save iptables rules
      command: iptables-save > /etc/sysconfig/iptables
      changed_when: false

    - name: Disable password authentication and enable key-based authentication for SSH
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Ensure public key authentication is enabled
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'
        state: present

    - name: Configure Fail2ban
      copy:
        src: /etc/fail2ban/jail.conf
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart Fail2ban

    - name: Obtain SSL certificate from Let's Encrypt
      command: certbot certonly --webroot -w /var/www/html -d your_domain.com --agree-tos --non-interactive --email your_email@domain.com

  handlers:
    - name: Restart Fail2ban
      systemd:
        name: fail2ban
        state: restarted
