- name: Centos pre-upgrade
  hosts: "{{ target_host }}"
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_prompt:
    - name: confirm_target
      prompt: "Is '{{ target_host }}' the correct target host? (yes/no)"
      private: no
  tasks:

    - name: Confirm target host
      fail:
        msg: "Aborted playbook execution. Confirm target host before proceeding."
      when: confirm_target != "yes"
        
    - name: Check CentOS version
      command: cat /etc/centos-release
      register: centos_release
      changed_when: false
      failed_when: false

    - name: Ensure playbook runs only on CentOS Stream 8
      fail:
        msg: "This playbook is intended to run on CentOS Stream 8 only."
      when: "'CentOS Stream release 8' not in centos_release.stdout"
        
    - name: Gather package facts
      package_facts:
        manager: auto
      register: package_facts

    - name: Check if PostgreSQL 15 is installed
      assert:
        that:
          - "'postgresql15-server' in package_facts.ansible_facts.packages"
        fail_msg: "This playbook is intended to run on machines with PostgreSQL 15 installed."

    - name: Create temp directory
      file:
        path: /var/temp/
        state: directory

    - name: Create files directory
      file:
        path: /var/temp/files/
        state: directory
          
    - name: Create backup directory
      file:
        path: /var/temp/backup/
        state: directory

    - name: Copy files to target
      synchronize:
        src: ~/files/  # Path to your files on the control node
        dest: /var/temp/files/       # Destination path on the target machine
        recursive: yes          

    - name: remove broken packages
      command: sudo yum -y remove iptables
      args:
        warn: false

    - name: remove broken packages
      dnf:
        name: make-devel-1:4.2.1-11.el8.x86_64 
        state: absent

    - name: clean yum
      command: /bin/yum clean all 
      args:
        warn: false
